### ISSUE TITLE
有几个错误的地方

### ISSUE THREAD

**Issue by tianshaokai** [wangyeming/FoxChat#1]
editContactPhoneNumAdapter.java 文件名字需要修改一下
第99行 Error:(99, 53) 错误: 不可比较的类型: Object和int

ContactDetailAdapter 第70行也报 Error:(70, 53) 错误: 不可比较的类型: Object和int 这个错误

**Comment by wangyeming** [comment]
谢谢指正，这个是我入行前写的练手的，现在看来代码烂的没法看了，谢谢你的指正！！

**Comment by tianshaokai** [comment]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/com.belerweb/pinyin4j/pom.properties
  	File1: /home/tianshaokai/.gradle/caches/modules-2/files-2.1/com.belerweb/pinyin4j/2.5.0/5a620aedec0f779f2123ba60fd4b74bfbd3e2646/pinyin4j-2.5.0.jar
  	File2: /home/tianshaokai/.gradle/caches/modules-2/files-2.1/com.belerweb/pinyin4j/2.5.0/5a620aedec0f779f2123ba60fd4b74bfbd3e2646/pinyin4j-2.5.0.jar

这个类库加载有点问题
